name: Compilation check

on:
    push:

jobs:

  compile_check:
    runs-on: ubuntu-20.04

    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install-go
        run: apt install golang
      - name: compile
        run: cd jtframe/src; go build .
